# Generated by Django 4.2.7 on 2023-11-09 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Addition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('air_pump', models.CharField(max_length=50, verbose_name='Air Pump')),
                ('electric_charging', models.CharField(max_length=50, verbose_name='E-charge')),
                ('resturants', models.CharField(max_length=50, verbose_name='Resturants')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=50, verbose_name='Street Name')),
                ('num', models.CharField(max_length=50, verbose_name='Street Number')),
                ('city', models.CharField(max_length=50, verbose_name='City')),
                ('state', models.CharField(max_length=50, verbose_name='State')),
                ('zip_code', models.CharField(max_length=50, verbose_name='Zip Code')),
                ('country', models.CharField(max_length=50, verbose_name='Country')),
            ],
        ),
        migrations.CreateModel(
            name='Gas_Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('additions', models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='station_tracker.addition', verbose_name='Additions')),
                ('location', models.ForeignKey(default='Unknown', on_delete=django.db.models.deletion.CASCADE, to='station_tracker.address', verbose_name='Location')),
            ],
        ),
    ]
