# Generated by Django 3.2.13 on 2023-11-23 12:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('station_tracker', '0002_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasstationowner',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gas_station_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
