# Generated by Django 4.2.7 on 2023-12-05 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('station_tracker', '0002_rewards'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('RewardType', models.CharField(max_length=200)),
                ('RewardPointsAmount', models.IntegerField()),
                ('RewardDescription', models.TextField()),
            ],
        ),
        migrations.RenameModel(
            old_name='Rewards',
            new_name='UserRewards',
        ),
        migrations.CreateModel(
            name='EarnRewards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MoneySpent', models.IntegerField(default=0)),
                ('GasStation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station_tracker.gas_station')),
                ('RewardType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='station_tracker.rewardtypes')),
            ],
        ),
    ]
