# Generated by Django 4.2.7 on 2023-12-06 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('station_tracker', '0003_gas_station_gasupdateid'),
        ('station_tracker', '0003_rewardtypes_rename_rewards_userrewards_earn_rewards'),
    ]

    operations = [
    ]
