# Generated by Django 3.2.13 on 2023-12-07 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('station_tracker', '0004_auto_20231206_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas_station',
            name='address',
            field=models.CharField(default='UCCS', max_length=100),
        ),
    ]
